version: '3'
volumes:
  node_modules:
services:
  api:
    build:
      context: ./api
    ports:
      - '3001:3001'
    volumes:
      - ./api:/app:cached
      - ./api/node_modules:/app/node_modules:cached
    links:
      - mongodb
      - minio
    working_dir: '/app'
    command: 'npm run start'
    environment:
      - MINIO_ENDPOINT
      - MINIO_ACCESS_KEY
      - MINIO_SECRET_KEY
      - MINIO_PAGE_BUCKET
      - MINIO_THUMBNAIL_BUCKET
      - MONGODB_HOST
      - MONGODB_PORT
      - MONGODB_DB
  frontend:
    build:
      context: ./frontend
    ports:
      - 1234:3000
    volumes:
      - ./frontend:/app:cached
      - ./frontend/node_modules:/app/node_modules:cached
    links:
      - api
      - mongodb
      - minio
    command: 'npm run start'
    environment:
      - PRIVATE_API_ENDPOINT
      - NEXT_PUBLIC_API_ENDPOINT
      - NEXT_PUBLIC_MINIO_ENDPOINT
      - NEXT_PUBLIC_MINIO_PAGE_BUCKET
      - NEXT_PUBLIC_MINIO_THUMBNAIL_BUCKET
  mongodb:
    image: mongo:3.2-jessie
    ports:
      - 27017:27017
    volumes:
      - ~/public/mangashuraku_data/mongodb:/data/db:cached
  elasticsearch:
    build:
      context: ./elasticsearch
    volumes:
      - ~public/mangashuraku_data/elasticsearch:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
  minio:
    image: minio/minio:RELEASE.2018-08-25T01-56-38Z
    volumes:
      # Sample
      - ~/public/mangashuraku_data/minio/data:/export:cached
      - ~/public/mangashuraku_data/minio/config:/root/.minio:cached
    ports:
      - 9000:9000
    environment:
      - MINIO_ACCESS_KEY
      - MINIO_SECRET_KEY
    command: server /export
