version: '3'

services:
  app:
    build: .
    ports:
      - '3001:3001'
    volumes:
      - ./:/app
    links:
      - mongo
      - minio
  mongo:
    image: mongo:latest
  minio:
    image: minio/minio:latest
    volumes:
      - ./data/minio/data:/export
      - ./data/minio/config:/root/.minio
    ports:
      - 9000:9000
    environment:
      MINIO_ACCESS_KEY: AKIA_MINIO_ACCESS_KEY
      MINIO_SECRET_KEY: minio_secret_key
    command: server /export
