version: '3'

services:
  app:
    build: .
    ports:
      - '3001:3001'
    volumes:
      - ./:/app
    links:
      - mongodb
      - minio
    working_dir: '/app'
    command: 'npm run start'
  mongodb:
    image: mongo:3.2-jessie
    ports:
      - 27017:27017
    volumes:
      - ./data/mongodb:/data/db
  minio:
    image: minio/minio:RELEASE.2018-08-25T01-56-38Z
    volumes:
      - ./data/minio/data:/export
      - ./data/minio/config:/root/.minio
    ports:
      - 9000:9000
    environment:
      MINIO_ACCESS_KEY: AKIA_MINIO_ACCESS_KEY
      MINIO_SECRET_KEY: minio_secret_key
    command: server /export
