version: '3'
volumes:
  node_modules:
services:
  api:
    build:
      context: ./api
    ports:
      - '3001:3001'
    volumes:
      - ./api:/app:cached
      - ./api/node_modules:/app/node_modules:cached
    links:
      - mongodb
      - minio
    working_dir: '/app'
    command: 'npm run start'
    environment:
      - MINIO_ENDPOINT=192.168.31.9:8000
  frontend:
    build:
      context: ./frontend
    ports:
      - 1234:1234
      - 45123:45123
    volumes:
      - ./frontend:/app:cached
      - ./frontend/node_modules:/app/node_modules:cached
    links:
      - api
      - mongodb
      - minio
    command: 'npm run start'
    environment:
      - API_ENDPOINT=192.168.31.9:3001
      - MINIO_ENDPOINT=192.168.31.9:8000
  mongodb:
    image: mongo:3.2-jessie
    ports:
      - 27017:27017
    volumes:
      - ./data/mongodb:/data/db:cached
  minio:
    image: minio/minio:RELEASE.2018-08-25T01-56-38Z
    volumes:
      - ./data/minio/data:/export:cached
      - ./data/minio/config:/root/.minio:cached
    ports:
      - 8000:9000
    environment:
      MINIO_ACCESS_KEY: AKIA_MINIO_ACCESS_KEY
      MINIO_SECRET_KEY: minio_secret_key
    command: server /export
