version: '3'

services:
  app:
    build: .
    ports:
      - '3001:3001'
    links:
      - mongo
      - minio
  mongo:
    image: mongo:latest
  minio:
    image: minio/minio:latest
    volumes:
      - ./data/minio/data:/export
      - ./data/minio/config:/root/.minio
    environment:
      MINIO_ACCESS_KEY: AKIA_MINIO_ACCESS_KEY
      MINIO_SECRET_KEY: minio_secret_key
    command: server /export
  nginx:
    build: './nginx'
    ports:
      - '8081:8081'
    volumes:
      - './nginx/logs:/var/log/nginx'
    links:
      - app
